### ISSUE TITLE
javascript errors empty (regression in 5.4.0)

### ISSUE THREAD

**Issue by pajod** [pickware/ShopwareStripePayment#102]
The transfer of error snippets (`frontend/plugins/payment/stripe_payment/digital_wallets` -- `error/*`) silently fails after a version 5.4.0 [change](https://github.com/pickware/ShopwareStripePayment/pull/88#discussion_r686357001) apparently motivated by a change in Shopware version 5.7.0

**Comment by svenmuennich** [comment]
Thank you for the bug report. We will look in to this as soon as possible.
