### ISSUE TITLE
StripePaymentAccount parent controller has a new constructor

### ISSUE THREAD

**Issue by Onein** [pickware/ShopwareStripePayment#116]
The Shopware_Controllers_Frontend_Account controller has a new constructor:
```
public function __construct(Shopware_Components_Config $config, CaptchaValidator $captchaValidator)
```
This results in an user facing error when navigating to the account credit card section, because the plugin extends the mentioned controller.

**Comment by grosssmutttr** [comment]
PUSH!

**Comment by svenmuennich** [comment]
Duplicate of https://github.com/pickware/ShopwareStripePayment/issues/118
