### ISSUE TITLE
The "Manage Credit Cards" button in the frontend does not work 

### ISSUE THREAD

**Issue by florianfaatz** [pickware/ShopwareStripePayment#118]
**How does the system behave currently?**

When logging in as a customer in the frontend and selecting the Manage Credit Card button, the following error message appears.

![image](https://user-images.githubusercontent.com/46442425/172380536-e7da871c-a084-4993-88eb-b1b027a8f248.png)

`Fatal error: Uncaught ArgumentCountError: Too few arguments to function Shopware_Controllers_Frontend_Account::__construct(), 0 passed in /var/www/engine/Library/Enlight/Controller/Dispatcher/Default.php on line 441 and exactly 2 expected in /var/www/engine/Shopware/Controllers/Frontend/Account.php:74`

Therefore, it is currently not possible for the customer to manage his credit cards. 

**How should the system behave?**

The correct interface should be displayed.

**Comment by Onein** [comment]
#116 duplicate

**Comment by lenaelkhouri** [comment]
bitte [Victor Lite von Code 108](https://pickware.zendesk.com/agent/tickets/120615) informieren.

**Comment by JanRogge** [comment]
Released mit v5.4.5
