### ISSUE TITLE
The manage credit card button doesn't work

### ISSUE THREAD

**Issue by maximiliankern** [pickware/ShopwareStripePayment#125]
How does the system behave currently?

When clicking on the Manage Credit Card button, the following error message appears. This was tested in the following setup:

- SW 5.5.10
- PHP 7.4.3
- Stripe 5.5.0

`Fatal error: Uncaught TypeError: Argument 1 passed to Enlight_Controller_Action::__construct() must implement interface Enlight_Controller_Request_Request, instance of Shopware_Components_Config given, called in /html/shopware5510/_testumgebung/engine/Shopware/Plugins/Community/Frontend/StripePayment/Controllers/Frontend/StripePaymentAccount.php on line 23 and defined in /html/shopware5510/_testumgebung/engine/Library/Enlight/Controller/Action.php:91 Stack trace: #0 /html/shopware5510/_testumgebung/engine/Shopware/Plugins/Community/Frontend/StripePayment/Controllers/Frontend/StripePaymentAccount.php(23): Enlight_Controller_Action->__construct(Object(Shopware_Components_Config), Object(Shopware\Components\Captcha\CaptchaValidator)) #1 /html/shopware5510/_testumgebung/engine/Library/Enlight/Controller/Dispatcher/Default.php(544): Shopware_Controllers_Frontend_StripePaymentAccount->__construct(Object(Enlight_Controller_Request_RequestHttp), Object(Enlight_Controller_Response_ResponseHttp)) #2 /html/shopware5510/_testumgebung in /html/shopware5510/_testumgebung/engine/Library/Enlight/Controller/Action.php on line 91`

Therefore, it is currently not possible for the customer to manage his credit cards.

How should the system behave?

The correct interface should be displayed.

**Comment by maximiliankern** [comment]
Erfolgreich getestet 🚀

**Comment by JanRogge** [comment]
Released mit v5.5.1
