### ISSUE TITLE
[SW5] No error message is displayed when the credit card payment gets rejected

### ISSUE THREAD

**Issue by maximiliankern** [pickware/ShopwareStripePayment#128]
Currently, no error message is displayed when the credit card gets rejected within the checkout. Hence, the customer does not know why the checkout wasn't successful. There should be an error message informing the customer that his checkout wasn't successful. Tested with SW 5.7.14 and 5.6.10

**Comment by JanRogge** [comment]
The problem only shows when a guest customer is used. With a logged in Customer there is an error message.

**Comment by maximiliankern** [comment]
As we remove the credit card information from the session for data protection reasons, we will not make any adjustments here.
