### ISSUE TITLE
Orders with a payment mean associated with stripe get created with dispatchId NULL

### ISSUE THREAD

**Issue by antoniokupresak** [pickware/ShopwareStripePayment#68]
Tested with the current master:

All orders that get created with a Stripe payment method "lose" their dispatch method, i.e. their `dispatchId` in `s_order` is NULL.

**Comment by JanRogge** [comment]
This seems to be a configuration error where no dispatch method was configured for the payment methods and there was no fallback dispatch method because of this the dispatchId was NULL.

**Comment by erikforss** [comment]
Since there seems nothing left to do here I will remove this issue from the Sprint Board.
