### ISSUE TITLE
Digital Wallet Payments use basketContent as is including items without prices

### ISSUE THREAD

**Issue by felixbrucker** [pickware/ShopwareStripePayment#77]
Currently we use the basketContent and each items `amountNumeric` as is:
https://github.com/pickware/ShopwareStripePayment/blob/5bb16df0bf18a44f47fd97dc1d786bae28d63cb3/Views/frontend/_public/src/javascript/stripe_payment_digital_wallets.js#L69-L74

As such it can happen that the `amountNumeric` is undefined and the JS script crashes. In this case it is not obvious to the buyer that apple pay / google pay is not working becaus no error is shown.

We should filter the items and only include items with a `amountNumeric` or `priceNumeric` set.
```js
this.paymentDisplayItems = config.basketContent
            .filter(function (item) {
                return item.amountNumeric || item.priceNumeric;
            })
            .map(function (item) {
                const itemPrice = parseFloat(item.amountNumeric || item.priceNumeric);

                return {
                    label: item.articlename,
                    amount: Math.round(itemPrice * 100),
                };
            });
```

**Comment by JanRogge** [comment]
I'm currently not sure who i can create items that produce this error so i will only create a draft PR till im able to verify the fix.

**Comment by felixbrucker** [comment]
I was unable to create items without an `amountNumeric` option as well, it might be that such items can only occur through 3rd party plugins.

**Comment by erikforss** [comment]
Completed
