### ISSUE TITLE
Klarna orders with redirect.status failed do not get handled correctly

### ISSUE THREAD

**Issue by antoniokupresak** [pickware/ShopwareStripePayment#86]
Klarna has two different redirect status: cancelled and failed. We currently do not handle failed correctly.

### Current Behavior:
The order gets created with payment state 35

### Desired Behavior: 
Orders with request state failed get handled the same way as orders with request state cancelled, i.e. the order state is -1.

### How to test:
You have to use an email address with "+denied" e.g. test+denied@example.com (see https://stripe.com/docs/sources/klarna#testing-klarna-payments)

**Comment by svenmuennich** [comment]
This should be fixed by #84.

**Comment by Onein** [comment]
Just to let you guys know, I've informed pickware support about this issue in june 2020, but sadly nothing happend.
