### ISSUE TITLE
[SW5] Payment request fails because localization of user is used instead of localization of billing company

### ISSUE THREAD

**Issue by erikforss** [pickware/ShopwareStripePayment#93]
To create a [payment request](https://stripe.com/docs/js/payment_request/create), information about the localization of the company that receives the payment is mandatory, to ensure that it is located in a country that is supported by Stripe.

However, in the Checkout process, we gather the information from the paying user and pass it as payment request, instead of the localization of the billing company.
This leads to an error, in case the user is located in a country, of which payments can be accepted, but that are not supported as company residence countries.

Wrong information about the country code is gathered here:
https://github.com/pickware/ShopwareStripePayment/blob/cb00b39f5b3a43d5f2b0a89ea09cf6dc72abebe8/Views/frontend/checkout/confirm.tpl#L84

**Comment by maximilianoster** [comment]
Betroffener Kunde (aus https://github.com/pickware/shopware-plugins/issues/1293): Herr Bertram von Famcapstore.com in https://pickware.zendesk.com/agent/tickets/103063

**Comment by ct-lh** [comment]
After having updated our plugin from v5.3.4 to v5.5.0 we were having issues with payments.

From my point of view, this change does not work properly when using accounts of different countries in different sub shops.

E.g:

Main Shop (ID 1) using a German Stripe Account
Sub Shop (ID 2) using a British Stripe Account

Wouldnt the setting always be reflecting the German accounts settings?
