### ISSUE TITLE
Provide documentation about the correct configuration of credit cards for using Google Pay

### ISSUE THREAD

**Issue by erikforss** [pickware/ShopwareStripePayment#94]
With the Stripe Plugin it is currently not possible to use credit cards, that are added using Google Pay App.
The credit cards **must** be added in the browser in browser-settings -> payment methods.

Otherwise the Stripe Plugin will tell the user, that Google Pay is not available in his browser.

We should provide some additional information in our documentation about that fact.
Below a screenshot of a credit card that was added directly in the browser and thus works correctly.
If a credit card was added using Google Pay App, it will have a note right behind its description saying "Google Pay" in the red box.
![image](https://user-images.githubusercontent.com/40789770/110828055-f3af7680-8296-11eb-8cf2-1540fb7cc8a9.png)

**Comment by jessicapleier** [comment]
Documentations have been updated:
[SW5](https://docs.google.com/document/d/1FfZU0AqEWtiXd7Ito6e7UiLzfpP5F_D8CT9gtogaZlk/edit#heading=h.labbbfk1ftlf) 
[SW6](https://docs.google.com/document/d/1Y6I9eFSpO-1QD73QOhYAA60AfI37MFHgmqiHiAPKcGk/edit#heading=h.5nbifwn4hvqm)
